name: CI Pipeline

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Verificar compilador
      run: g++ --version

    - name: Compilar testes
      run: |
        g++ tests/BancoTest.cpp \
        src/business/Banco.cpp \
        src/business/ServicoBanco.cpp \
        src/model/Conta.cpp \
        src/model/ContaBonus.cpp \
        src/model/ContaPoupanca.cpp \
        -Iinclude \
        -o testes

    - name: Executar testes
      run: ./testes