name: Release Pipeline

on:
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++ \
            cppcheck \
            zip

      - name: Compilar projeto
        run: |
          g++ tests/BancoTest.cpp \
          src/business/Banco.cpp \
          src/business/ServicoBanco.cpp \
          src/model/Conta.cpp \
          src/model/ContaBonus.cpp \
          src/model/ContaPoupanca.cpp \
          -Iinclude \
          -o testes

      - name: Analise estatica
        run: |
          cppcheck src include \
            --enable=all \
            --suppress=missingIncludeSystem \
            --error-exitcode=0

      - name: Executar testes
        run: ./testes

      - name: Gerar Release
        id: release
        run: |

          git fetch --all --tags

          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"

          echo "Branch origem: $SOURCE_BRANCH"

          LAST_TAG=$(git tag | grep "^rel-" | sort -V | tail -n 1)

          if [ -z "$LAST_TAG" ]; then

            NEW_TAG="rel-1.0"

          else

            VERSION=${LAST_TAG#rel-}

            IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"

            X=${VERSION_PARTS[0]}
            Y=${VERSION_PARTS[1]}
            Z=${VERSION_PARTS[2]}

            [ -z "$X" ] && X=1
            [ -z "$Y" ] && Y=0
            [ -z "$Z" ] && Z=0

            if [[ "$SOURCE_BRANCH" == "staging" ]]; then

              Y=$((Y + 1))
              NEW_TAG="rel-$X.$Y"

            elif [[ "$SOURCE_BRANCH" == hotfix/* ]]; then

              if [[ "$LAST_TAG" =~ ^rel-[0-9]+\.[0-9]+$ ]]; then
                Z=1
              else
                Z=$((Z + 1))
              fi

              NEW_TAG="rel-$X.$Y.$Z"

            else

              echo "Release só pode ser criada a partir de staging ou hotfix/*."
              exit 1

            fi

          fi

          echo "Nova Release: $NEW_TAG"

          echo "tag=$NEW_TAG" >> "$GITHUB_OUTPUT"

          if git tag -l | grep -q "^${NEW_TAG}$"; then
            echo "Tag já existe."
            exit 1
          fi

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

          echo "Release criada com sucesso."

      - name: Gerar pacote ZIP
        run: |
          zip -r "${{ steps.release.outputs.tag }}.zip" \
            src \
            include \
            tests \
            README.md

      - name: Publicar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.release.outputs.tag }}
          path: ${{ steps.release.outputs.tag }}.zip